# Converts a compiled SPIR-V binary into a C++ header holding a byte array.
# Bytes (not uint32 words) sidestep endianness concerns in the generator; the
# consumer memcpys into a std::vector<uint32_t>, which is valid because SPIR-V
# is defined as a little-endian word stream and every supported target is
# little-endian.
#
# Usage: cmake -DINPUT=<file.spv> -DOUTPUT=<file.h> -DSYMBOL=<name> -P embed_spirv.cmake

file(READ "${INPUT}" hex_content HEX)
string(LENGTH "${hex_content}" hex_length)
math(EXPR byte_count "${hex_length} / 2")

string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex_content}")

file(WRITE "${OUTPUT}"
"// Generated by cmake/embed_spirv.cmake from ${INPUT}. Do not edit.
#pragma once
#include <cstddef>
inline constexpr unsigned char ${SYMBOL}[] = {${bytes}};
inline constexpr size_t ${SYMBOL}_size = ${byte_count};
")
