function(velox_read_version header output)
    file(READ "${header}" contents)
    foreach(component Major Minor Patch)
        string(REGEX MATCH "kVersion${component} = ([0-9]+)" match "${contents}")
        if(NOT match)
            message(FATAL_ERROR "velox: failed to read kVersion${component} from ${header}")
        endif()
        set(version_${component} "${CMAKE_MATCH_1}")
    endforeach()
    set(${output} "${version_Major}.${version_Minor}.${version_Patch}" PARENT_SCOPE)
endfunction()
